-- IRCS Athlete Tracker schema
-- Run once in Supabase → SQL Editor → New query → Run

-- Athletes
create table if not exists public.athletes (
  id bigint generated by default as identity primary key,
  name text not null,
  period text not null,
  type text not null,
  sport text not null default '—',
  grad integer
);

-- Performance test entries
create table if not exists public.test_entries (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references public.athletes(id) on delete cascade,
  date date not null,
  bw numeric,
  fly numeric,
  jump numeric,
  rsi numeric,
  bsq numeric,
  bench numeric,
  tbdl numeric,
  sbdl numeric,
  m400 numeric,
  unique (athlete_id, date)
);

-- Dress code logs (one code per athlete per day)
create table if not exists public.dress_logs (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references public.athletes(id) on delete cascade,
  date date not null,
  code text not null,
  unique (athlete_id, date)
);

-- Attendance logs (one status per athlete per day)
create table if not exists public.attendance_logs (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references public.athletes(id) on delete cascade,
  date date not null,
  status text not null,
  unique (athlete_id, date)
);

-- Participation logs (one code per athlete per day)
-- LE = Lack of Effort, CNP = Choose Not to Participate
create table if not exists public.participation_logs (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references public.athletes(id) on delete cascade,
  date date not null,
  code text not null,
  unique (athlete_id, date)
);

-- Notes
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references public.athletes(id) on delete cascade,
  date date not null,
  issue text not null,
  action text not null,
  notes text not null default '',
  done boolean not null default false
);

-- Expose tables to the Data API (anon / authenticated)
grant select, insert, update, delete on public.athletes to anon, authenticated, service_role;
grant select, insert, update, delete on public.test_entries to anon, authenticated, service_role;
grant select, insert, update, delete on public.dress_logs to anon, authenticated, service_role;
grant select, insert, update, delete on public.attendance_logs to anon, authenticated, service_role;
grant select, insert, update, delete on public.participation_logs to anon, authenticated, service_role;
grant select, insert, update, delete on public.notes to anon, authenticated, service_role;

grant usage, select on all sequences in schema public to anon, authenticated, service_role;

alter table public.athletes enable row level security;
alter table public.test_entries enable row level security;
alter table public.dress_logs enable row level security;
alter table public.attendance_logs enable row level security;
alter table public.participation_logs enable row level security;
alter table public.notes enable row level security;

-- Open policies (no login). Tighten later if you add Auth.
drop policy if exists "athletes_all" on public.athletes;
create policy "athletes_all" on public.athletes for all to anon, authenticated using (true) with check (true);

drop policy if exists "test_entries_all" on public.test_entries;
create policy "test_entries_all" on public.test_entries for all to anon, authenticated using (true) with check (true);

drop policy if exists "dress_logs_all" on public.dress_logs;
create policy "dress_logs_all" on public.dress_logs for all to anon, authenticated using (true) with check (true);

drop policy if exists "attendance_logs_all" on public.attendance_logs;
create policy "attendance_logs_all" on public.attendance_logs for all to anon, authenticated using (true) with check (true);

drop policy if exists "participation_logs_all" on public.participation_logs;
create policy "participation_logs_all" on public.participation_logs for all to anon, authenticated using (true) with check (true);

drop policy if exists "notes_all" on public.notes;
create policy "notes_all" on public.notes for all to anon, authenticated using (true) with check (true);

-- Seed roster (skip if already populated)
insert into public.athletes (id, name, period, type, sport, grad) values
  (1,  'Brown, Easton',     '1', 'Weight Training', 'Football', 2028),
  (2,  'Caruso, Tyler',     '1', 'Weight Training', 'Track',    2028),
  (3,  'Hill, Oliver',      '1', 'Weight Training', 'Soccer',   2027),
  (4,  'Stibbard, Sheldon', '2', 'Weight Training', 'Football', 2026),
  (5,  'Stiles, Ethan',     '2', 'Weight Training', 'Football', 2027),
  (6,  'Thibeault, Ty',     '2', 'Weight Training', 'Football', 2028),
  (7,  'Taylor, Reed',      '3', 'Weight Training', 'Football', 2027),
  (8,  'Victor, Elijah',    '3', 'Weight Training', 'Football', 2028),
  (9,  'Victor, Jadyn',     '3', 'Weight Training', 'Football', 2027),
  (10, 'Powers, Logan',     '5', 'HOPE Fitness',    '—',        2028),
  (11, 'Sullivan, Liam',    '5', 'HOPE Fitness',    '—',        2027),
  (12, 'Cox, Logan',        '6', 'Weight Training', 'Football', 2027),
  (13, 'Hagood, Benjamin',  '6', 'Weight Training', 'Football', 2026),
  (14, 'Hingson, Isaac',    '6', 'Weight Training', 'Football', 2027),
  (15, 'Martinez, Quinn',   '6', 'Weight Training', 'Football', 2028),
  (16, 'Meade, Carter',     '8', 'Weight Training', 'Soccer',   2027),
  (17, 'Wodnicki, Gabriel', '8', 'Weight Training', 'Soccer',   2028)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.athletes', 'id'), greatest((select max(id) from public.athletes), 1));

insert into public.test_entries (id, athlete_id, date, bw, fly, jump, rsi, bsq, bench, tbdl, sbdl, m400) values
  (1,  12, '2026-01-22', 195, 1.14, 23.6, 0.52, null, 275, null, 315, 72.0),
  (2,  12, '2026-03-04', 215, 1.11, 26.1, 0.61, 320,  325, 455,  455, 74.1),
  (3,  15, '2026-01-22', 155, 1.16, 20.9, 0.55, null, 185, 405,  250, null),
  (4,  15, '2026-03-04', 163, 1.10, 22.3, 0.58, 295,  205, 425,  295, 73.4),
  (5,  13, '2026-01-22', 185, 1.25, 22.1, 0.57, 275,  145, 275,  365, null),
  (6,  13, '2026-03-04', 211, 1.20, 24.0, 0.62, 365,  215, 425,  365, null),
  (7,  14, '2026-01-22', 190, 1.33, 18.9, 0.49, 225,  155, 315,  225, null),
  (8,  14, '2026-03-04', 220, 1.28, 21.2, 0.54, 335,  205, 315,  335, null),
  (9,  4,  '2026-01-22', 158, 1.20, 20.5, 0.51, 165,  135, 225,  165, 76.0),
  (10, 5,  '2026-01-22', 130, 1.17, 19.2, 0.48, 245,  205, 285,  295, 78.0)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.test_entries', 'id'), greatest((select max(id) from public.test_entries), 1));

insert into public.dress_logs (athlete_id, date, code) values
  (1, '2026-08-13', 'NS'),
  (3, '2026-08-11', 'NSH'),
  (3, '2026-08-14', 'NP'),
  (4, '2026-08-12', 'WP')
on conflict (athlete_id, date) do nothing;

insert into public.attendance_logs (athlete_id, date, status) values
  (1,  '2026-08-11', 'P'),
  (1,  '2026-08-12', 'P'),
  (1,  '2026-08-13', 'A'),
  (1,  '2026-08-14', 'P'),
  (3,  '2026-08-11', 'T'),
  (3,  '2026-08-12', 'P'),
  (3,  '2026-08-14', 'E'),
  (12, '2026-08-11', 'P'),
  (12, '2026-08-12', 'P'),
  (12, '2026-08-13', 'P'),
  (12, '2026-08-14', 'P')
on conflict (athlete_id, date) do nothing;

insert into public.notes (id, athlete_id, date, issue, action, notes, done) values
  (1, 3, '2026-08-14', '2nd dress violation (NSH + NP)', 'email',    '',          false),
  (2, 1, '2026-08-13', 'No shirt 1st offense',            'referral', 'Sent 8/15', true)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.notes', 'id'), greatest((select max(id) from public.notes), 1));
